theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from

# Configuração para páginas
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Impede que o README.md seja usado como índice
include: ["teste.html"]
